version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ip_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ipdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
